version: '3'

services:

  # Services

  redis:
    build: ./containers/redis/
    ports:
      - "6379:6379"

  mosquitto:
    image: toke/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  # verdaccio:
  #   image: verdaccio/verdaccio
  #   ports:
  #     - "4873:4873"
