version: '3'

services:

  # Services

  redis:
    build: ./containers/redis/
    ports:
      - "6379:6379"

  mosquitto:
    image: toke/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  orderbook:
    build: ./containers/orderbook
    ports:
      - "80:80"
    links:
      - redis
      - mosquitto
    environment:
      - ENV=production
      - REDIS_URL=redis://redis:6379
      - MQTT_URL=mqtt://mosquitto:1883
