version: '3'

services:

  # Services

  redis:
    build: ./containers/redis
    ports:
      - "6379:6379"

  mosquitto:
    image: toke/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  #

  http-server:
    build: ./containers/http-server
    links:
      - redis
    environment:
      - ENV=production
      - REDIS_URL=redis://redis:6379
      - NODE_PORT=80
    ports:
      - "8080:80"
