version: '3'

services:

  # Services

  redis:
    image: redis:5
    ports:
      - "6379:6379"

  mosquitto:
    image: toke/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  #

  # http-server:
  #   build: ./containers/http-server
  #   links:
  #     - redis
  #   environment:
  #     - ENV=production
  #     - REDIS_URL=redis://redis:6379
  #     - NODE_PORT=80
  #   ports:
  #     - "8080:80"
  #
  # mqtt-producer:
  #   build: ./containers/mqtt-producer
  #   links:
  #     - redis
  #     - mosquitto
  #   environment:
  #     - ENV=production
  #     - REDIS_URL=redis://redis:6379
  #     - MQTT_URL=mqtt://mosquitto:1883

  lymex-bitfinex-btc-usd:
    build: ./connectors/lymex
    links:
      - redis
    environment:
      - ENV=production
      - REDIS_URL=redis://redis:6379
      - BROKER=bitfinex
      - SYMBOl=btc-usd

  lymex-bitfinex-eth-usd:
    build: ./connectors/lymex
    links:
      - redis
    environment:
      - ENV=production
      - REDIS_URL=redis://redis:6379
      - BROKER=bitfinex
      - SYMBOl=eth-usd
