version: '3'

services:

  # Services

  redis:
    build: ./containers/redis
    ports:
      - "6379:6379"

  mosquitto:
    image: toke/mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"

  #

  http-server:
    build: ./containers/http-server
    links:
      - redis
    environment:
      - ENV=production
      - REDIS_URL=redis://redis:6379
      - NODE_PORT=80
    ports:
      - "8080:80"

  mqtt-producer:
    build: ./containers/mqtt-producer
    links:
      - redis
      - mosquitto
    environment:
      - ENV=production
      - REDIS_URL=redis://redis:6379
      - MQTT_URL=mqtt://mosquitto:1883

  remote-connector-cexio-btc-usd:
    build: ./containers/remote-connector-cexio
    links:
      - redis
    environment:
      - ENV=production
      - REDIS_URL=redis://redis:6379
      - CEXIO_API_KEY=lT8rhvimwK7R4IyJfXNjWNMu140
      - CEXIO_API_SECRET=5ATNU7Xm3UYZhGThIoAXiMTD4
      - SYMBOl=btc-usd

  remote-connector-cexio-eth-usd:
    build: ./containers/remote-connector-cexio
    links:
      - redis
    environment:
      - ENV=production
      - REDIS_URL=redis://redis:6379
      - CEXIO_API_KEY=lT8rhvimwK7R4IyJfXNjWNMu140
      - CEXIO_API_SECRET=5ATNU7Xm3UYZhGThIoAXiMTD4
      - SYMBOL=eth-usd
